export type SpellAnimationSlug = {
  styleSlug: string;
  spellSlug: string;
};

const DISPLAY_TEXT_TO_SLUG: Record<string, SpellAnimationSlug> = {
  // Rogue
  "水之呼吸 · 水面斩": { styleSlug: "water_breathing", spellSlug: "water_surface_slash" },
  "风之呼吸 · 投刃": { styleSlug: "wind_breathing", spellSlug: "wind_throwing_blade" },
  "雷之呼吸 · 鸣神": { styleSlug: "thunder_breathing", spellSlug: "thunder_narukami" },
  "兽之呼吸 · 切裂": { styleSlug: "beast_breathing", spellSlug: "beast_cutting_rend" },
  "蛇之呼吸 · 狭头毒牙": { styleSlug: "serpent_breathing", spellSlug: "serpent_narrow_head_venom_fang" },
  "兽之呼吸 · 狂裂": { styleSlug: "beast_breathing", spellSlug: "beast_wild_rend" },
  "蛇之呼吸 · 委蛇斩": { styleSlug: "serpent_breathing", spellSlug: "serpent_meandering_slash" },
  "蛇之呼吸 · 巢绞": { styleSlug: "serpent_breathing", spellSlug: "serpent_nest_strangle" },
  "虫之呼吸 · 百足蛇腹": { styleSlug: "insect_breathing", spellSlug: "insect_centipede_belly" },
  "虫之呼吸 · 蜂牙之舞": { styleSlug: "insect_breathing", spellSlug: "insect_bee_fang_dance" },
  "兽之呼吸 · 圆转旋牙": { styleSlug: "beast_breathing", spellSlug: "beast_circular_spinning_fang" },
  "雷之呼吸 · 霹雳一闪": { styleSlug: "thunder_breathing", spellSlug: "thunder_thunderclap_flash" },
  "霞之呼吸 · 胧": { styleSlug: "mist_breathing", spellSlug: "mist_oboro" },
  "霞之呼吸 · 霞散飞沫": { styleSlug: "mist_breathing", spellSlug: "mist_scattering_splash" },
  "月之呼吸 · 穿面斩": { styleSlug: "moon_breathing", spellSlug: "moon_piercing_face_slash" },
  "霞之呼吸 · 垂天远霞": { styleSlug: "mist_breathing", spellSlug: "mist_distant_heaven_haze" },
  "霞之呼吸 · 月之霞消": { styleSlug: "mist_breathing", spellSlug: "mist_lunar_haze_dissolve" },
  "雷之呼吸 · 神速": { styleSlug: "thunder_breathing", spellSlug: "thunder_godspeed" },
  "日之呼吸 · 幻日虹": { styleSlug: "sun_breathing", spellSlug: "sun_fake_rainbow" },
  "虫之呼吸 · 蝶之舞": { styleSlug: "insect_breathing", spellSlug: "insect_butterfly_dance" },
  "岩之呼吸 · 天面碎": { styleSlug: "stone_breathing", spellSlug: "stone_sky_surface_smash" },
  "虫之呼吸 · 戏弄": { styleSlug: "insect_breathing", spellSlug: "insect_tease" },
  "霞之呼吸 · 八重霞": { styleSlug: "mist_breathing", spellSlug: "mist_eightfold_mist" },

  // Breathing catalog from design/ds_skills.md. These may use font fallback until
  // a matching per-spell text triplet is generated.
  "日之呼吸 · 碧罗之天": { styleSlug: "sun_breathing", spellSlug: "sun_blue_heaven" },
  "日之呼吸 · 烈日红镜": { styleSlug: "sun_breathing", spellSlug: "sun_red_mirror" },
  "日之呼吸 · 火车": { styleSlug: "sun_breathing", spellSlug: "sun_fire_wheel" },
  "日之呼吸 · 灼骨炎阳": { styleSlug: "sun_breathing", spellSlug: "sun_scorching_bone_sun" },
  "日之呼吸 · 阳华突": { styleSlug: "sun_breathing", spellSlug: "sun_sunflower_thrust" },
  "日之呼吸 · 飞轮阳炎": { styleSlug: "sun_breathing", spellSlug: "sun_flying_wheel_haze" },
  "日之呼吸 · 斜阳转身": { styleSlug: "sun_breathing", spellSlug: "sun_setting_sun_transform" },
  "日之呼吸 · 辉辉恩光": { styleSlug: "sun_breathing", spellSlug: "sun_beneficent_radiance" },
  "日之呼吸 · 日晕之龙·头舞": { styleSlug: "sun_breathing", spellSlug: "sun_halo_dragon_head_dance" },
  "日之呼吸 · 炎舞": { styleSlug: "sun_breathing", spellSlug: "sun_flame_dance" },
  "日之呼吸 · 第十三型": { styleSlug: "sun_breathing", spellSlug: "sun_thirteenth_form" },
  "日之呼吸 · 圆舞一闪": { styleSlug: "sun_breathing", spellSlug: "sun_round_dance_flash" },
  "日之呼吸 · 火之神神乐·十三之型": { styleSlug: "sun_breathing", spellSlug: "sun_hinokami_kagura_thirteenth" },
  "火之神神乐·十三之型": { styleSlug: "sun_breathing", spellSlug: "sun_hinokami_kagura_thirteenth" },
  "火之神神乐 · 十三之型": { styleSlug: "sun_breathing", spellSlug: "sun_hinokami_kagura_thirteenth" },

  "月之呼吸 · 暗月·宵之宫": { styleSlug: "moon_breathing", spellSlug: "moon_dark_moon_evening_palace" },
  "月之呼吸 · 常世孤月·无间": { styleSlug: "moon_breathing", spellSlug: "moon_lonely_moon_incessant" },
  "月之呼吸 · 厄镜·月映": { styleSlug: "moon_breathing", spellSlug: "moon_moonlit_mirror" },
  "月之呼吸 · 月龙轮尾": { styleSlug: "moon_breathing", spellSlug: "moon_dragon_ringtail" },
  "月之呼吸 · 降月·连面": { styleSlug: "moon_breathing", spellSlug: "moon_descending_moon_continuous_faces" },
  "月之呼吸 · 穿面斩·萝月": { styleSlug: "moon_breathing", spellSlug: "moon_piercing_face_slash_luo_moon" },
  "月之呼吸 · 月虹·片割之月": { styleSlug: "moon_breathing", spellSlug: "moon_rainbow_half_moon" },

  "水之呼吸 · 水车": { styleSlug: "water_breathing", spellSlug: "water_water_wheel" },
  "水之呼吸 · 流流舞动": { styleSlug: "water_breathing", spellSlug: "water_flowing_dance" },
  "水之呼吸 · 打潮": { styleSlug: "water_breathing", spellSlug: "water_striking_tide" },
  "水之呼吸 · 干天之慈雨": { styleSlug: "water_breathing", spellSlug: "water_blessed_rain" },
  "水之呼吸 · 扭转漩涡": { styleSlug: "water_breathing", spellSlug: "water_twisting_whirlpool" },
  "水之呼吸 · 雫波纹击刺": { styleSlug: "water_breathing", spellSlug: "water_drop_ripple_thrust" },
  "水之呼吸 · 泷壶": { styleSlug: "water_breathing", spellSlug: "water_waterfall_basin" },
  "水之呼吸 · 水流飞沫·乱": { styleSlug: "water_breathing", spellSlug: "water_splashing_water_flow_turbulent" },
  "水之呼吸 · 生生流转": { styleSlug: "water_breathing", spellSlug: "water_constant_flux" },
  "水之呼吸 · 凪": { styleSlug: "water_breathing", spellSlug: "water_dead_calm" },

  "炎之呼吸 · 不知火": { styleSlug: "flame_breathing", spellSlug: "flame_unknown_fire" },
  "炎之呼吸 · 升炎天": { styleSlug: "flame_breathing", spellSlug: "flame_rising_scorching_sun" },
  "炎之呼吸 · 气炎万象": { styleSlug: "flame_breathing", spellSlug: "flame_blazing_universe" },
  "炎之呼吸 · 盛炎涡旋": { styleSlug: "flame_breathing", spellSlug: "flame_blooming_flame_undulation" },
  "炎之呼吸 · 炎虎": { styleSlug: "flame_breathing", spellSlug: "flame_flame_tiger" },
  "炎之呼吸 · 炼狱": { styleSlug: "flame_breathing", spellSlug: "flame_rengoku" },

  "雷之呼吸 · 稻魂": { styleSlug: "thunder_breathing", spellSlug: "thunder_rice_spirit" },
  "雷之呼吸 · 聚蚊成雷": { styleSlug: "thunder_breathing", spellSlug: "thunder_swarm_thunder" },
  "雷之呼吸 · 热界雷": { styleSlug: "thunder_breathing", spellSlug: "thunder_heat_lightning" },
  "雷之呼吸 · 火雷神": { styleSlug: "thunder_breathing", spellSlug: "thunder_flaming_thunder_god" },
  "雷之呼吸 · 霹雳一闪·二连": { styleSlug: "thunder_breathing", spellSlug: "thunder_thunderclap_flash_twofold" },
  "雷之呼吸 · 霹雳一闪·六连": { styleSlug: "thunder_breathing", spellSlug: "thunder_thunderclap_flash_sixfold" },
  "雷之呼吸 · 霹雳一闪·八连": { styleSlug: "thunder_breathing", spellSlug: "thunder_thunderclap_flash_eightfold" },
  "雷之呼吸 · 霹雳一闪·神速": { styleSlug: "thunder_breathing", spellSlug: "thunder_godspeed" },

  "风之呼吸 · 尘旋风·削": { styleSlug: "wind_breathing", spellSlug: "wind_dust_whirlwind_cut" },
  "风之呼吸 · 爪爪·科户风": { styleSlug: "wind_breathing", spellSlug: "wind_claws_purifying_wind" },
  "风之呼吸 · 升上沙尘岚": { styleSlug: "wind_breathing", spellSlug: "wind_rising_dust_storm" },
  "风之呼吸 · 黑风烟岚": { styleSlug: "wind_breathing", spellSlug: "wind_black_wind_smoke_storm" },
  "风之呼吸 · 初烈风斩": { styleSlug: "wind_breathing", spellSlug: "wind_primary_gale_slash" },
  "风之呼吸 · 韦驮天台风": { styleSlug: "wind_breathing", spellSlug: "wind_idaten_typhoon" },

  "岩之呼吸 · 流纹岩·速征": { styleSlug: "stone_breathing", spellSlug: "stone_volcanic_rock_rapid_conquest" },

  "花之呼吸 · 御影梅": { styleSlug: "flower_breathing", spellSlug: "flower_honorable_shadow_plum" },
  "花之呼吸 · 红花衣": { styleSlug: "flower_breathing", spellSlug: "flower_crimson_hanagoromo" },
  "花之呼吸 · 徒之芍药": { styleSlug: "flower_breathing", spellSlug: "flower_peony_of_futility" },
  "花之呼吸 · 涡桃": { styleSlug: "flower_breathing", spellSlug: "flower_whirling_peach" },
  "花之呼吸 · 雫波纹击刺": { styleSlug: "flower_breathing", spellSlug: "flower_drop_ripple_thrust" },
  "花之呼吸 · 彼岸朱眼": { styleSlug: "flower_breathing", spellSlug: "flower_equinoctial_vermilion_eye" },

  "虫之呼吸 · 蝶之舞·戏弄": { styleSlug: "insect_breathing", spellSlug: "insect_butterfly_dance_tease" },
  "虫之呼吸 · 蜈蚣之舞·百足蛇腹": { styleSlug: "insect_breathing", spellSlug: "insect_centipede_dance_belly" },

  "蛇之呼吸 · 颈蛇双生": { styleSlug: "serpent_breathing", spellSlug: "serpent_twin_headed_serpent" },
  "蛇之呼吸 · 蜿蜿长蛇": { styleSlug: "serpent_breathing", spellSlug: "serpent_slithering_serpent" },

  "恋之呼吸 · 初恋战栗": { styleSlug: "love_breathing", spellSlug: "love_first_love_tremors" },
  "恋之呼吸 · 懊恼巡恋": { styleSlug: "love_breathing", spellSlug: "love_pangs_of_love" },
  "恋之呼吸 · 恋猫时雨": { styleSlug: "love_breathing", spellSlug: "love_catlove_shower" },
  "恋之呼吸 · 摇曳恋情·乱爪": { styleSlug: "love_breathing", spellSlug: "love_swaying_love_wildclaw" },
  "恋之呼吸 · 猫足恋风": { styleSlug: "love_breathing", spellSlug: "love_catleg_lovewind" },

  "音之呼吸 · 响斩无间": { styleSlug: "sound_breathing", spellSlug: "sound_constant_resounding_slashes" },
  "音之呼吸 · 鸣弦奏奏": { styleSlug: "sound_breathing", spellSlug: "sound_string_performance" },

  "兽之呼吸 · 穿刺": { styleSlug: "beast_breathing", spellSlug: "beast_pierce" },
  "兽之呼吸 · 啮裂": { styleSlug: "beast_breathing", spellSlug: "beast_bite_rend" },
  "兽之呼吸 · 切细裂": { styleSlug: "beast_breathing", spellSlug: "beast_slice_to_pieces" },
  "兽之呼吸 · 空间识觉": { styleSlug: "beast_breathing", spellSlug: "beast_spatial_awareness" },
  "兽之呼吸 · 伸·蜿裂": { styleSlug: "beast_breathing", spellSlug: "beast_extend_bendy_slash" },
  "兽之呼吸 · 投裂": { styleSlug: "beast_breathing", spellSlug: "beast_throwing_rend" },
  "兽之呼吸 · 飞掷噬咬": { styleSlug: "beast_breathing", spellSlug: "beast_throwing_bite" },

  // Blood Elf racial
  "血鬼术 · 魔力紊乱": { styleSlug: "blood_art", spellSlug: "blood_mana_disruption" },

  // Blood art catalog from design/ds_skills.md.
  "血鬼术 · 分裂逃生": { styleSlug: "blood_art", spellSlug: "blood_split_escape" },
  "血鬼术 · 莲叶冰": { styleSlug: "blood_art", spellSlug: "blood_lotus_leaf_ice" },
  "血鬼术 · 枯园垂": { styleSlug: "blood_art", spellSlug: "blood_barren_hanging_garden" },
  "血鬼术 · 冻云": { styleSlug: "blood_art", spellSlug: "blood_freezing_cloud" },
  "血鬼术 · 寒烈白姬": { styleSlug: "blood_art", spellSlug: "blood_cold_white_princess" },
  "血鬼术 · 散莲华": { styleSlug: "blood_art", spellSlug: "blood_scattering_lotus" },
  "血鬼术 · 结晶御子": { styleSlug: "blood_art", spellSlug: "blood_crystal_child" },
  "血鬼术 · 雾冰·睡莲菩萨": { styleSlug: "blood_art", spellSlug: "blood_rime_sleeping_lotus_bodhisattva" },
  "血鬼术 · 破坏杀·空式": { styleSlug: "blood_art", spellSlug: "blood_hakai_air_type" },
  "血鬼术 · 破坏杀·脚式·冠先割": { styleSlug: "blood_art", spellSlug: "blood_hakai_leg_crown_split" },
  "血鬼术 · 破坏杀·脚式·流闪群光": { styleSlug: "blood_art", spellSlug: "blood_hakai_leg_flowing_flash" },
  "血鬼术 · 破坏杀·脚式·飞游星千轮": { styleSlug: "blood_art", spellSlug: "blood_hakai_leg_flying_star_wheel" },
  "血鬼术 · 破坏杀·碎式·万叶闪柳": { styleSlug: "blood_art", spellSlug: "blood_hakai_crushing_willow" },
  "血鬼术 · 破坏杀·乱式": { styleSlug: "blood_art", spellSlug: "blood_hakai_disorder" },
  "血鬼术 · 破坏杀·鬼芯八重芯": { styleSlug: "blood_art", spellSlug: "blood_hakai_demon_core" },
  "血鬼术 · 破坏杀·终式·青银乱残光": { styleSlug: "blood_art", spellSlug: "blood_hakai_final_blue_silver" },
  "血鬼术 · 无限城操纵": { styleSlug: "blood_art", spellSlug: "blood_infinity_castle_control" },
  "血鬼术 · 狂压鸣波": { styleSlug: "blood_art", spellSlug: "blood_crushing_sound_wave" },
  "血鬼术 · 狂鸣雷杀": { styleSlug: "blood_art", spellSlug: "blood_mad_thunder_kill" },
  "血鬼术 · 激泪刺突": { styleSlug: "blood_art", spellSlug: "blood_tears_piercing_thrust" },
  "血鬼术 · 水狱钵": { styleSlug: "blood_art", spellSlug: "blood_water_prison_pot" },
  "血鬼术 · 千本针鱼杀": { styleSlug: "blood_art", spellSlug: "blood_thousand_needle_fish" },
  "血鬼术 · 蛸壶地狱": { styleSlug: "blood_art", spellSlug: "blood_octopus_pot_hell" },
  "血鬼术 · 阵杀鱼鳞": { styleSlug: "blood_art", spellSlug: "blood_murderous_fish_scales" },
  "血鬼术 · 一万滑空粘鱼": { styleSlug: "blood_art", spellSlug: "blood_ten_thousand_gliding_fish" },
  "血鬼术 · 神之手": { styleSlug: "blood_art", spellSlug: "blood_hand_of_god" },
  "血鬼术 · 八重带斩": { styleSlug: "blood_art", spellSlug: "blood_eightfold_sash_slash" },
  "血鬼术 · 衣带操控": { styleSlug: "blood_art", spellSlug: "blood_sash_control" },
  "血鬼术 · 飞血镰": { styleSlug: "blood_art", spellSlug: "blood_flying_blood_sickle" },
  "血鬼术 · 血镰攻击": { styleSlug: "blood_art", spellSlug: "blood_sickle_attack" },
  "血鬼术 · 电击生成": { styleSlug: "blood_art", spellSlug: "blood_electric_generation" },
  "血鬼术 · 强制昏睡催眠的细语": { styleSlug: "blood_art", spellSlug: "blood_forced_sleep_whisper" },
  "血鬼术 · 强制昏睡睡眠·眼": { styleSlug: "blood_art", spellSlug: "blood_forced_sleep_eye" },
  "血鬼术 · 梦境之绳": { styleSlug: "blood_art", spellSlug: "blood_dream_rope" },
  "血鬼术 · 列车融合": { styleSlug: "blood_art", spellSlug: "blood_train_fusion" },
  "血鬼术 · 破坏精神之核": { styleSlug: "blood_art", spellSlug: "blood_spiritual_core_destruction" },
  "血鬼术 · 杀目笼": { styleSlug: "blood_art", spellSlug: "blood_murderous_eye_basket" },
  "血鬼术 · 溶解之茧": { styleSlug: "blood_art", spellSlug: "blood_dissolving_cocoon" },
  "血鬼术 · 斑毒痰": { styleSlug: "blood_art", spellSlug: "blood_mottled_poison_spit" },
  "血鬼术 · 丝线操控": { styleSlug: "blood_art", spellSlug: "blood_thread_control" },
  "血鬼术 · 肉体强化": { styleSlug: "blood_art", spellSlug: "blood_body_reinforcement" },
  "血鬼术 · 分裂": { styleSlug: "blood_art", spellSlug: "blood_splitting" },
  "血鬼术 · 复数手臂": { styleSlug: "blood_art", spellSlug: "blood_multiple_arms" },
  "血鬼术 · 尚速鼓打": { styleSlug: "blood_art", spellSlug: "blood_drum_beating" },
  "血鬼术 · 手鞠破坏": { styleSlug: "blood_art", spellSlug: "blood_temari_destruction" },
  "血鬼术 · 虏获腔·影狼": { styleSlug: "blood_art", spellSlug: "blood_shadow_wolf" },
  "血鬼术 · 战祸阵狼": { styleSlug: "blood_art", spellSlug: "blood_war_disaster_wolf" },
  "血鬼术 · 幻境": { styleSlug: "blood_art", spellSlug: "blood_illusion_realm" },
  "血鬼术 · 空间操纵": { styleSlug: "blood_art", spellSlug: "blood_space_manipulation" },
  "血鬼术 · 视觉梦幻之香": { styleSlug: "blood_art", spellSlug: "blood_visual_dream_scent" },
  "血鬼术 · 白日魔香": { styleSlug: "blood_art", spellSlug: "blood_daylight_scent" },
  "血鬼术 · 纸眼": { styleSlug: "blood_art", spellSlug: "blood_paper_eye" },
  "血鬼术 · 木根生长": { styleSlug: "blood_art", spellSlug: "blood_root_growth" },

  // Death Knight
  "月之呼吸 · 月魄灾涡": { styleSlug: "moon_breathing", spellSlug: "moon_soul_calamity_vortex" },
  "兽之呼吸 · 乱杭咬": { styleSlug: "beast_breathing", spellSlug: "beast_chaotic_fang_bite" },
  "日之呼吸 · 圆舞": { styleSlug: "sun_breathing", spellSlug: "sun_round_dance" },
  "血鬼术 · 爆血": { styleSlug: "blood_art", spellSlug: "blood_blood_burst" },
  "岩之呼吸 · 岩躯之肤": { styleSlug: "stone_breathing", spellSlug: "stone_rock_skin" },
  "血鬼术 · 跋弧跳梁": { styleSlug: "blood_art", spellSlug: "blood_leaping_stride" },
  "血鬼术 · 圆斩旋回·飞血镰": { styleSlug: "blood_art", spellSlug: "blood_spinning_blood_scythe" },
  "月之呼吸 · 珠华弄月": { styleSlug: "moon_breathing", spellSlug: "moon_pearl_moon_play" },
  "雷之呼吸 · 电轰雷轰": { styleSlug: "thunder_breathing", spellSlug: "thunder_lightning_roar" },
  "月之呼吸 · 凶变·天满纤月": { styleSlug: "moon_breathing", spellSlug: "moon_heavenly_full_moon" },
  "血鬼术 · 冬零冰柱": { styleSlug: "blood_art", spellSlug: "blood_winter_pillar" },
  "风之呼吸 · 木枯风袭": { styleSlug: "wind_breathing", spellSlug: "wind_cold_tree_wind" },
  "霞之呼吸 · 移流斩": { styleSlug: "mist_breathing", spellSlug: "mist_flowing_slash" },
  "霞之呼吸 · 霞海之海": { styleSlug: "mist_breathing", spellSlug: "mist_sea_of_haze" },
  "风之呼吸 · 晴岚风树": { styleSlug: "wind_breathing", spellSlug: "wind_clear_storm_tree" },
  "血鬼术 · 刻丝牢": { styleSlug: "blood_art", spellSlug: "blood_thread_prison" },
  "岩之呼吸 · 蛇纹岩·双极": { styleSlug: "stone_breathing", spellSlug: "stone_serpent_rock_twin" },
  "血鬼术 · 破坏杀·灭式": { styleSlug: "blood_art", spellSlug: "blood_hakai_annihilation" },
  "虫之呼吸 · 蜻蛉之舞·复眼六角": { styleSlug: "insect_breathing", spellSlug: "insect_dragonfly_hex_eyes" },
  "虫之呼吸 · 蜂牙之舞·真靡": { styleSlug: "insect_breathing", spellSlug: "insect_bee_fang_true_sway" },
  "月之呼吸 · 厌忌月·销蚀": { styleSlug: "moon_breathing", spellSlug: "moon_engraved_moon_corrosion" },
  "血鬼术 · 蔓莲华": { styleSlug: "blood_art", spellSlug: "blood_vine_lotus" },
  "血鬼术 · 生物操纵": { styleSlug: "blood_art", spellSlug: "blood_bio_manipulation" },
  "血鬼术 · 憎珀天": { styleSlug: "blood_art", spellSlug: "blood_hatred_golem" },
  "兽之呼吸 · 爆裂猛进": { styleSlug: "beast_breathing", spellSlug: "beast_explosive_rush" },
  "风之呼吸 · 劲风·天狗风": { styleSlug: "wind_breathing", spellSlug: "wind_tengu_gale" },
  "音之呼吸 · 轰": { styleSlug: "sound_breathing", spellSlug: "sound_roar" },
  "血鬼术 · 红洁之矢": { styleSlug: "blood_art", spellSlug: "blood_crimson_arrow" },
  "血鬼术 · 无间业树": { styleSlug: "blood_art", spellSlug: "blood_karmic_tree" },
  "血鬼术 · 破坏杀·罗针": { styleSlug: "blood_art", spellSlug: "blood_hakai_compass" },
  "血鬼术 · 惑血·融通无碍之香": { styleSlug: "blood_art", spellSlug: "blood_bewitching_scent" },
  "血鬼术 · 刻丝轮转": { styleSlug: "blood_art", spellSlug: "blood_thread_spin" },
  "血鬼术 · 粉冻": { styleSlug: "blood_art", spellSlug: "blood_powder_frost" },
  "血鬼术 · 黑血枳棘": { styleSlug: "blood_art", spellSlug: "blood_black_blood_thorn" },
  "岩之呼吸 · 瓦轮刑部": { styleSlug: "stone_breathing", spellSlug: "stone_wheel_punishment" },
  "雷之呼吸 · 远雷": { styleSlug: "thunder_breathing", spellSlug: "thunder_distant_lightning" }
};

export function resolveSpellAnimationSlug(displayText: string): SpellAnimationSlug | undefined {
  return DISPLAY_TEXT_TO_SLUG[displayText];
}
